version: '3.8'
services:
  webserver:
    image: nginx:1.19-alpine
    working_dir: /var/www
    ports:
      - 8000:80
    volumes:
      - './src:/var/www'
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./docker/php
    working_dir: /var/www
    volumes:
      - './src:/var/www'
      - './docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
  # MySQL container
  # db:
  #   image: mysql:8.0
  #   volumes:
  #     - ./docker/data/mysql:/var/lib/mysql
  #   restart: always
  #   env_file:
  #   - ./var.env
  #   ports:
  #     - 3306:3306